version: "3.9"
services:
  web:
    build: .
    command: npm start
    ports:
      - 3333:3333
    
  mongo:
    image: mongo:4.4.18
    restart: always
    env_file:
      - .env
    volumes:
      - ~/mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
