version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volume:
      - mongodb:/data/db
    

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

volumes:
  mongodb:
