- name: Start all docker containers
  hosts: prd
  tasks:
    - name: Clone the repo
      git:
        repo: https://github.com/milad7212/back-ready.git
        dest: /home/milad/back-ready

    - name: Copy the .env file
      copy:
        src: /home/milad/.env
        dest: /home/milad/back-ready/.env
        remote_src: true

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/milad/back-ready
      register: output

    - ansible.builtin.debug:
        var: output
